# Extends jupyter/datascience-notebook
FROM jupyter/datascience-notebook

# Copies example Jupyter notebook
COPY MongoDB.ipynb /home/jovyan/MongoDB.ipynb

# Installs pymongo library
RUN pip install pymongo
